### ISSUE TITLE
Accept all .clj* kind of files

### ISSUE THREAD

**Issue by helins** [lambdaisland/garden-watcher#6]
The current implementation translates namespaces to `.clj` files only, meaning one cannot work with `.cljs` and `.cljc` files. It would be especially useful to handle `.cljc` files in order to easily share CSS data between static style sheet and UI code.

This problem was mentioned on Slack and I open this issue so it is not forgotten. Although the fix does not seem complex, I don't have much time currently.

**Comment by plexus** [comment]
As mentioned on Slack, a PR for this would be most appreciated. It should be a fairly small fix.
